<?php
defined('BASEPATH') OR exit('No direct script access allowed');
use Restserver\Libraries\REST_Controller;
require APPPATH . '/libraries/REST_Controller.php';
require APPPATH . '/libraries/Format.php';
class Webservice extends REST_Controller{

    public function __construct() {
        parent::__construct();
        $this->methods['test_get']['limit'] = 1; // 500 requests per hour per user/key
        $this->methods['users_post']['limit'] = 500; // 500 requests per hour per user/key
        $this->load->database();
        $this->load->helper('url');
    }

    public function test_get($dd){

        $dt=array(
            "hola"=>"ff",
            "dd"=>array(1,2),
            "cal"=>$dd
        );
        $this->response($dt);
    }
    public function users_post(){
        // $this->some_model->update_user( ... );
        $message = [
            'id' => 100, // Automatically generated by the model
            'name' => $this->post('name'),
            'email' => $this->post('email'),
            'message' => 'Added a resource'
        ];

        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }

}